branches:
  only:
    - master

language: cpp

git:
  depth: 10
  submodules: true

jobs:
  include:
    - name: Build on Linux
      os: linux
      dist: jammy
      before_install:
        - export WDIR=$(pwd)
      script:
        - chmod +x builder/run/linux.sh builder/checkout-deps.sh builder/package.sh builder/patches/*.sh
        - builder/run/linux.sh
