#!/usr/bin/env bash
set -euo pipefail

PACKAGE_DIR="${1:?package directory required}"
SOURCEMOD_DIR="${2:?sourcemod directory required}"
BUILDER_DIR="${3:?builder directory required}"
DEPS_DIR="${4:-$(cd "$BUILDER_DIR/.." && pwd)/deps}"

SM_ROOT="$PACKAGE_DIR/addons/sourcemod"
GAMEDATA_ROOT="$SM_ROOT/gamedata"
TRANSLATIONS_REF="${TRANSLATIONS_REF:-master}"

keep_gamedata=(
  core.games/blacklist.plugins.txt
  core.games/common.games.txt
  core.games/engine.ep1.txt
  core.games/master.games.txt
  funcommands.games.txt
  sdkhooks.games/common.games.txt
  sdkhooks.games/game.cstrike.txt
  sdkhooks.games/master.games.txt
  sdktools.games/common.games.txt
  sdktools.games/engine.ep1.txt
  sdktools.games/game.cstrike.txt
  sdktools.games/master.games.txt
  sm-cstrike.games/game.cstrike.txt
  sm-cstrike.games/master.games.txt
)

echo "==> Stripping Linux binaries" >&2
if [ "${BUILD_PLATFORM:-linux}" != "windows" ]; then
  while IFS= read -r -d '' binary; do
    strip --strip-unneeded "$binary"
  done < <(find "$SM_ROOT/bin" "$SM_ROOT/extensions" -type f \( -name '*.so' -o -name 'spcomp' \) -print0)
fi

echo "==> Trimming gamedata to CS:S v34 layout" >&2
if [ -d "$GAMEDATA_ROOT" ]; then
  while IFS= read -r -d '' file; do
  rel="${file#"$GAMEDATA_ROOT"/}"
  keep=0
  for allowed in "${keep_gamedata[@]}"; do
    if [ "$rel" = "$allowed" ]; then
      keep=1
      break
    fi
  done
  if [ "$keep" -eq 0 ]; then
    rm -f "$file"
  fi
  done < <(find "$GAMEDATA_ROOT" -type f -print0)

  mkdir -p "$GAMEDATA_ROOT/sm-cstrike.games"
  if [ -f "$GAMEDATA_ROOT/sm-cstrike.games/game.css.txt" ]; then
    mv -f "$GAMEDATA_ROOT/sm-cstrike.games/game.css.txt" \
      "$GAMEDATA_ROOT/sm-cstrike.games/game.cstrike.txt"
  fi
  rm -f "$GAMEDATA_ROOT/sm-cstrike.games/game.csgo.txt"
  cp -f "$BUILDER_DIR/assets/gamedata/sm-cstrike.games/game.cstrike.txt" \
    "$GAMEDATA_ROOT/sm-cstrike.games/game.cstrike.txt"
  cp -f "$BUILDER_DIR/assets/gamedata/sm-cstrike.games/master.games.txt" \
    "$GAMEDATA_ROOT/sm-cstrike.games/master.games.txt"
fi

echo "==> Patching core.cfg for CS:S v34 release layout" >&2
core_cfg="$SM_ROOT/configs/core.cfg"
if [ -f "$core_cfg" ]; then
  sed -i 's/^\(\s*"DisableAutoUpdate"\s*\)"no"/\1"yes"/' "$core_cfg"
fi

echo "==> Fetching upstream translations" >&2
translations_dir="$DEPS_DIR/sourcemod-translations"
rm -rf "$translations_dir"
git clone --depth 1 --filter=blob:none --sparse \
  https://github.com/alliedmodders/sourcemod "$translations_dir"
git -C "$translations_dir" sparse-checkout set translations
if [ "$TRANSLATIONS_REF" != "master" ]; then
  git -C "$translations_dir" fetch --depth 1 origin "$TRANSLATIONS_REF"
  git -C "$translations_dir" checkout "$TRANSLATIONS_REF"
fi

rm -rf "$SM_ROOT/translations"
cp -a "$translations_dir/translations" "$SM_ROOT/translations"

if [ ! -f "$SM_ROOT/scripting/include/version_auto.inc" ]; then
  inc_dir="$SOURCEMOD_DIR/build/includes"
  if [ -f "$inc_dir/version_auto.inc" ]; then
    cp -f "$inc_dir/version_auto.inc" "$SM_ROOT/scripting/include/version_auto.inc"
  else
    echo "warning: version_auto.inc was not generated by the build" >&2
  fi
fi

echo "==> Package prepared" >&2
