#!/usr/bin/env bash
# Write css34_build_stamp.h into SourceMod / Metamod public trees so
# `sm version` / `meta version` show the packaging + upstream commits.
set -euo pipefail

WDIR="${WDIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
SOURCEMOD_DIR="${SOURCEMOD_DIR:-$WDIR/sourcemod}"
MMS_DIR="${MMS_DIR:-$WDIR/deps/mmsource-1.10}"
SOURCEMOD_COMMIT="${SOURCEMOD_COMMIT:-832519ab647cdecb85763918dbfed1cb5e79c6cb}"
MMS_COMMIT="${MMS_COMMIT:-80e8ff0be3b62386bbd6f937e97b819ef8be6dd2}"

if git -C "$WDIR" rev-parse HEAD >/dev/null 2>&1; then
  CSS34_PACK_COMMIT="$(git -C "$WDIR" rev-parse HEAD)"
else
  CSS34_PACK_COMMIT="unknown"
fi

# Prefer the real checked-out SHAs when trees exist.
if [[ -d "$SOURCEMOD_DIR/.git" ]] || [[ -f "$SOURCEMOD_DIR/.git" ]]; then
  SOURCEMOD_COMMIT="$(git -C "$SOURCEMOD_DIR" rev-parse HEAD 2>/dev/null || echo "$SOURCEMOD_COMMIT")"
fi
if [[ -d "$MMS_DIR/.git" ]]; then
  MMS_COMMIT="$(git -C "$MMS_DIR" rev-parse HEAD 2>/dev/null || echo "$MMS_COMMIT")"
fi

write_stamp() {
  local out="$1"
  mkdir -p "$(dirname "$out")"
  cat >"$out" <<EOF
/* Auto-generated by builder/write-build-stamps.sh — do not edit. */
#ifndef CSS34_BUILD_STAMP_H_
#define CSS34_BUILD_STAMP_H_

#define CSS34_PACK_COMMIT       "${CSS34_PACK_COMMIT}"
#define CSS34_UPSTREAM_SM_COMMIT "${SOURCEMOD_COMMIT}"
#define CSS34_UPSTREAM_MM_COMMIT "${MMS_COMMIT}"

#endif /* CSS34_BUILD_STAMP_H_ */
EOF
  echo "==> Wrote $out"
  echo "    CSS34_PACK_COMMIT=${CSS34_PACK_COMMIT}"
  echo "    CSS34_UPSTREAM_SM_COMMIT=${SOURCEMOD_COMMIT}"
  echo "    CSS34_UPSTREAM_MM_COMMIT=${MMS_COMMIT}"
}

if [[ -d "$SOURCEMOD_DIR/public" ]]; then
  write_stamp "$SOURCEMOD_DIR/public/css34_build_stamp.h"
fi
if [[ -d "$MMS_DIR/public" ]]; then
  write_stamp "$MMS_DIR/public/css34_build_stamp.h"
fi
